import {
  ActionEvents,
  ActionSchema,
  BatcherEvents,
  BuilderEvents,
  FIFOStrategy,
  MicroRollup,
} from "@stackr/stackr-js";
import bodyParser from "body-parser";
import express, { Request, Response } from "express";
import cors from "cors";
import { stackrConfig } from "../stackr.config";
import { ByteCodeRollup, byteCodeSTF } from "./state";
import { StateMachine } from "@stackr/stackr-js/execution";

// this file is generated by the deployment script
import * as genesisState from "../genesis-state.json";

const rollup = async () => {
  const counterFsm = new StateMachine({
    state: new ByteCodeRollup(genesisState.state),
    stf: byteCodeSTF,
  });

  const actionSchemaType = {
    type: "String",
    id: "Uint",
    byteCode: "String",
    programCounter: "Uint",
    transactionData: {
      id: "Uint",
      type: "String",
      hashs: "String",
    },
  };

  const actionInput = new ActionSchema("update-state", actionSchemaType);

  const buildStrategy = new FIFOStrategy();

  const { state, actions, events } = await MicroRollup({
    config: stackrConfig,
    useState: counterFsm,
    useAction: actionInput,
    useBuilder: { strategy: buildStrategy, autorun: true },
    useSyncer: { autorun: true },
  });

  events.action.onEvent(ActionEvents.SUBMIT_ACTION, (action) => {
    console.log("action submitted", action);
  });

  events.batcher.onEvent(BatcherEvents.BATCH_ACTION, (batch) => {
    console.log("action batched", batch);
  });

  events.builder.onEvent(BuilderEvents.ORDER_BATCH, (batch) => {
    console.log("action batch ordered", batch);
  });

  return { state, actions };
};

const app = express();
app.use(bodyParser.json());
app.use(cors());
const { actions, state } = await rollup();

app.get("/", (req: Request, res: Response) => {
  res.send({ currentCount: state.get().state.getState() });
});

app.post("/", async (req: Request, res: Response) => {
  const schema = actions.getSchema("update-state");

  if (!schema) {
    res.status(400).send({ message: "error" });
    return;
  }

  try {
    const newAction = schema.newAction(req.body);
    const ack = await actions.submit(newAction);
    res.status(201).send({ ack });
  } catch (e: any) {
    res.status(400).send({ error: e.message });
  }
});

app.listen(3000, () => {
  console.log("listening on port 3000");
});

// actionEventsEmitter.on(ActionEvents.SUBMIT_ACTION, (data) => {
//   console.log("submit_action - Event triggered : ", data.payload);
// });

// executorEventsEmitter.on(ExecutorEvents.EXECUTE_SINGLE, (data) => {
//   console.log("execute_single - Event triggered : ", data);
// });
